plugins {
    id "java"
    id "application"
}

application {
    mainClass = "com.WOA.Oasis.desktop.DesktopLauncher"
    applicationDefaultJvmArgs = ["-XstartOnFirstThread"]   // ⭐⭐⭐ macOS 必加
}

dependencies {
    implementation project(":core")
    implementation "com.badlogicgames.gdx:gdx-backend-lwjgl3:1.14.0"
    implementation "com.badlogicgames.gdx:gdx-platform:1.14.0:natives-desktop"
}

sourceSets.main.resources.srcDirs = ["../core/assets"]