plugins {
    id "java"
    id "application"
}

application {
    mainClass = "com.WOA.Oasis.desktop.DesktopLauncher"

    // 只在 macOS 添加这个参数
    if (System.getProperty("os.name").toLowerCase().contains("mac")) {
        applicationDefaultJvmArgs = ["-XstartOnFirstThread"]
    }
}

dependencies {
    implementation project(":core")
    implementation "com.badlogicgames.gdx:gdx-backend-lwjgl3:1.14.0"
    implementation "com.badlogicgames.gdx:gdx-platform:1.14.0:natives-desktop"
}

sourceSets.main.resources.srcDirs = ["../core/assets"]
